### ISSUE TITLE
About the time test

### ISSUE THREAD

**Issue by kakaxi314** [laggui/pytorch-cpp#1]
I found you directly used time.time() to calculate time in your code.
However, it's not accurate in GPU mode.
`torch.cuda.synchronize()` should be added to get precise time.
From my test, the jit version is a little slower in fact?

**Comment by laggui** [comment]
Yes, I just wanted to get a quick idea of the timings for testing purposes. But with your suggestion I will check this out using `torch.cuda.synchronize()` to get a more precise timing.

Thanks a lot for the suggestion! I'll get back to you with the updated results, as I am interested in comparing the timing performance between the two :)

**Comment by laggui** [comment]
@kakaxi314 I just updated the repo and the results. My Torch Script model is, on average, very slightly faster (excluding the first forward pass). But honestly the difference is a lot more minimal than I would have hoped!
